# Generated by Django 5.0.6 on 2024-07-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
